@ParqueoApi_HostAddress = http://localhost:5000

### 1. Estado y Bienvenida
GET {{ParqueoApi_HostAddress}}/
Accept: application/json

### 2. Registrar entrada de vehículo
POST {{ParqueoApi_HostAddress}}/api/vehiculos/entrada
Content-Type: application/json

{
  "placa": "P-123ABC"
}

### 3. Registrar salida de vehículo por Id
PUT {{ParqueoApi_HostAddress}}/api/vehiculos/salida/1
Content-Type: application/json

### 4. Consultar todos los registros de vehículos
GET {{ParqueoApi_HostAddress}}/api/vehiculos
Accept: application/json

### 5. Consultar vehículos activos (Vista)
GET {{ParqueoApi_HostAddress}}/api/vehiculos/activos
Accept: application/json

### 6. Consultar historial de ocupación
GET {{ParqueoApi_HostAddress}}/api/vehiculos/historial
Accept: application/json
